function result = parameters_struct_validate( p )

    if numel(p) > 1
        result = arrayfun( @situate.parameters_struct_validate, p );
    elseif iscell(p)
        result = cellfun( @situate.parameters_struct_validate, p );
    else
      
        required_fields = { ...
            'description', ...
            'num_iterations', ...
            'agent_pool_adjustment_function', ...
            'agent_pool_initialization_function', ...
            'num_scouts', ...
            'agent_urgency_defaults', ...
            'use_direct_scout_to_workspace_pipe', ...
            'stopping_condition', ...
            'situation_model', ...
            'classifier', ...
            'external_support_function_description', ...
            'external_support_function', ...
            'total_support_function_description', ...
            'total_support_function', ...
            'situation_grounding_function_description', ...
            'situation_grounding_function', ...
            'thresholds', ...
            'adjustment_model', ...
            'temperature', ...
            'situation_description',...
            'situation_objects', ...
            'situation_objects_possible_labels', ...
            'situation_objects_urgency_pre', ...
            'situation_objects_urgency_post', ...
            'seed_test', ...
            'use_visualizer', ...
            'viz_options', ...
            'situation_description' };

        cur_fields = fields(p);

        missing_fields = setsub( required_fields, cur_fields );

        if( isempty( missing_fields ) )
            result = true;
        else
            result = false;
        end
        
    end
    
end