global dog_svm_model walker_svm_model leash_svm_model cnn_net cnn_layer;
load(strcat('/stash/mm-group/evan/crop_learn/models/svm_','dog','.mat'),'svm_model');
dog_svm_model = svm_model;
load(strcat('/stash/mm-group/evan/crop_learn/models/svm_','walker','.mat'),'svm_model');
walker_svm_model = svm_model;
load(strcat('/stash/mm-group/evan/crop_learn/models/svm_','leash','.mat'),'svm_model');
leash_svm_model = svm_model;
here = pwd;
cd '/u/eroche/matlab/cnn/matconvnet-1.0-beta20/';
disp('Starting MatConvNet');
run matlab/vl_setupnn;
cnn_net = vl_simplenn_tidy(load('imagenet-vgg-f.mat'));
cnn_layer = 18;
cnn_net.layers = cnn_net.layers(1:cnn_layer);
cd (here);  